# Generated by Django 3.2.5 on 2021-11-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('country', models.CharField(blank=True, max_length=124, null=True)),
                ('city', models.CharField(blank=True, max_length=124, null=True)),
                ('lattitude', models.FloatField(blank=True, null=True)),
                ('longtitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Energy_intake_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('uom', models.CharField(choices=[('Nm3', 'Nm3'), ('Liter', 'Liter'), ('MWh', 'MWh'), ('TJ', 'TJ')], default='MWh', max_length=12)),
                ('year', models.IntegerField()),
                ('emission_factor', models.FloatField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
    ]
