# Generated by Django 3.2.5 on 2021-11-16 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emissions_source_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('uom', models.CharField(choices=[('Nm3', 'Nm3'), ('Liter', 'Liter'), ('MWh', 'MWh'), ('TJ', 'TJ')], default='MWh', max_length=12)),
                ('year', models.IntegerField()),
                ('emission_factor', models.FloatField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
            options={
                'unique_together': {('plant', 'name', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='Energy_intake_item',
        ),
    ]
