# Generated by Django 3.2.5 on 2021-11-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20211116_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plant',
            new_name='Terminal',
        ),
        migrations.RenameField(
            model_name='emissions_source_item',
            old_name='plant',
            new_name='terminal',
        ),
        migrations.AlterUniqueTogether(
            name='emissions_source_item',
            unique_together={('terminal', 'name', 'year')},
        ),
    ]
