# Generated by Django 3.2.5 on 2021-11-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20211118_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminal',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
