# Generated by Django 3.2.5 on 2021-11-30 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_rename_longtitude_terminal_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emissions_source_item',
        ),
    ]
