# Generated by Django 3.2.5 on 2022-01-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_delete_emissions_source_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieselGenerator', models.BooleanField(default=False)),
                ('fireFightEquipment', models.BooleanField(default=False)),
                ('processPumpsElectric', models.BooleanField(default=False)),
                ('processPumpsDiesel', models.BooleanField(default=False)),
                ('airCompressor', models.BooleanField(default=False)),
                ('VCU', models.BooleanField(default=False)),
                ('RTO', models.BooleanField(default=False)),
                ('VRU', models.BooleanField(default=False)),
                ('Terminal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminale', to='plants.terminal')),
            ],
        ),
    ]
