# Generated by Django 3.2.5 on 2022-01-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_terminalequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalequipment',
            name='heatedStorage',
            field=models.BooleanField(default=False),
        ),
    ]
