# Generated by Django 3.2.5 on 2022-01-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_terminalequipment_heatedstorage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminalequipment',
            old_name='Terminal',
            new_name='terminal',
        ),
    ]
