# Generated by Django 3.2.5 on 2022-01-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0005_delete_emissions_source_item'),
        ('energypurchase', '0002_alter_purchased_utility_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('current_situation', models.TextField(blank=True, null=True)),
                ('improved_situation', models.TextField(blank=True, null=True)),
                ('risks', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('utility_reduction', models.FloatField(blank=True, null=True)),
                ('investment', models.FloatField(blank=True, null=True)),
                ('impact_OPEX', models.CharField(choices=[('inc', 'Increase'), ('decr', 'Decrease'), ('none', 'None')], default='none', max_length=5)),
                ('impact_CAPEX', models.CharField(choices=[('inc', 'Increase'), ('decr', 'Decrease'), ('none', 'None')], default='none', max_length=5)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal', to='plants.terminal')),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility', to='energypurchase.purchased_utility')),
            ],
        ),
    ]
