export const ActionTypes = {
    SET_TERMINALS: "SET_TERMINALS",
    SELECTED_TERMINAL: "SELECTED_TERMINAL",
    SELECTED_TERMINAL_ENERGY: "SELECTED_TERMINAL_ENERGY",
    // REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  };