# Generated by Django 3.2.5 on 2021-11-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0005_delete_emissions_source_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchased_utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('year', models.IntegerField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('emission_factor', models.FloatField(blank=True, null=True)),
                ('uom', models.CharField(choices=[('Nm3', 'Nm3'), ('Liter', 'Liter'), ('MWh', 'MWh'), ('TJ', 'TJ')], default='MWh', max_length=12)),
                ('price', models.FloatField(blank=True, null=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.terminal')),
            ],
            options={
                'unique_together': {('terminal', 'name', 'year')},
            },
        ),
    ]
