# Generated by Django 3.2.5 on 2021-12-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energypurchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_utility',
            name='uom',
            field=models.CharField(choices=[('Nm3', 'Nm3'), ('Liter', 'Liter'), ('MWh', 'MWh'), ('TJ', 'TJ'), ('Other', 'OTH')], default='MWh', max_length=12),
        ),
    ]
